version: '3.8'

services:
  backend:
    platform: linux/arm64
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/app

  frontend:
    platform: linux/arm64
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    platform: linux/arm64
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  db_data: