services:
  db:
    image: postgres:15
    container_name: finance_db
    restart: always
    env_file:
      - ./backend/.env  
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - finance_network

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: finance_backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:app
    networks:
      - finance_network

  frontend:
    build: 
      context: ./frontend
      dockerfile: dockerfile
    container_name: finance_frontend
    restart: always
    ports:
    - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - finance_network

networks:
  finance_network:

volumes:
  postgres_data:

    
