# Generated by Django 5.1.3 on 2025-01-28 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataUpload', '0002_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='dataUpload.category'),
        ),
    ]
