# Generated by Django 5.1.3 on 2025-01-28 08:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataUpload', '0003_alter_keyword_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together={('user', 'words')},
        ),
    ]
