# Generated by Django 5.1.3 on 2025-02-17 08:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataUpload', '0005_alter_keyword_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together={('user', 'words')},
        ),
    ]
