# Generated by Django 5.1.3 on 2025-01-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataUpload', '0007_alter_category_name_alter_category_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=255),
        ),
    ]
