# Generated by Django 5.1.3 on 2025-02-26 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataUpload', '0009_alter_keyword_unique_together'),
        ('dataUpload', '0009_keyword_user_alter_keyword_word_and_more'),
    ]

    operations = [
    ]
