# Generated by Django 5.1.3 on 2025-01-21 21:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataUpload', '0002_usercategory_userkeyword'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userkeyword',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userkeyword',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userkeyword',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='csvdata',
            unique_together={('user', 'id')},
        ),
        migrations.DeleteModel(
            name='UserCategory',
        ),
        migrations.DeleteModel(
            name='UserKeyword',
        ),
    ]
