# Generated by Django 5.1.3 on 2025-01-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataUpload', '0004_usercategory_alter_csvdata_category_userkeyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='userkeyword',
            name='user_category',
        ),
        migrations.AlterUniqueTogether(
            name='userkeyword',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userkeyword',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='csvdata',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='UserCategory',
        ),
        migrations.DeleteModel(
            name='UserKeyword',
        ),
    ]
